-- MySQL Script generated by MySQL Workbench
-- Κυρ 17 Ιουλ 2022 06:00:38 μμ EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL auto_increment,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `tin` VARCHAR(10) NOT NULL,
  `admin` TINYINT NOT NULL,
  `accepted` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `id` INT NOT NULL auto_increment,
  `name` VARCHAR(45) NOT NULL,
  `first_bid` INT NULL,
  `buy_price` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `img_path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL auto_increment,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`item_category` ;

CREATE TABLE IF NOT EXISTS `mydb`.`item_category` (
  `category_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `item_id`),
  INDEX `fk_item_category_item1_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_category_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `mydb`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bids`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bids` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bids` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bids_item1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`bidder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bidder` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bidder` (
  `id` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `rating` float NULL,
  INDEX `fk_bidder_users_idx` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bidder_users`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`bid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`bid` ;

CREATE TABLE IF NOT EXISTS `mydb`.`bid` (
  `id` INT NOT NULL auto_increment,
  `time` TIME NOT NULL,
  `amount` INT NOT NULL,
  `bids_id` INT NOT NULL,
  `bidder_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bid_bids1_idx` (`bids_id` ASC) VISIBLE,
  CONSTRAINT `fk_bid_bids1`
    FOREIGN KEY (`bids_id`)
    REFERENCES `mydb`.`bids` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  INDEX `fk_bid_bidder1_idx` (`bidder_id` ASC) VISIBLE,
  CONSTRAINT `fk_bid_bidder1`
    FOREIGN KEY (`bidder_id`)
    REFERENCES `mydb`.`bidder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


DROP TABLE IF EXISTS `mydb`.`reviews` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reviews`
(
    `user_id`   int not null,
    `bidder_id` int not null,
    `review`    text,
    `rating`    float not null,
    INDEX `fk_reviews_users_bidders_idx` (`user_id` ASC, `bidder_id` ASC) VISIBLE,
    PRIMARY KEY (`user_id`, `bidder_id`),
    CONSTRAINT `fk_reviews_users`
        FOREIGN KEY (`user_id`)
            REFERENCES `mydb`.`users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_reviews_bidders`
        FOREIGN KEY (`bidder_id`)
            REFERENCES `mydb`.`bidder` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
